### ISSUE TITLE
Install with packer

### ISSUE THREAD

**Issue by floydj** [vim-fuzzbox/fuzzbox.vim#7]
Is it possible? I'm using:

```lua
  use { 'Donaldttt/fuzzyy'}
```

And Packer shows it's installing it with no warnings or errors. But none of the Fuzzy* commands actually work:
```
Not an editor command: FuzzyFiles
```

Am I missing something? I'm using Neovim, if that matters.

**Comment by debajyoti1990** [comment]
If my understanding is correct then this plugin will not work in neovim because it is written in Vim9. Of course @Donaldttt  can clarify formally.

**Comment by Donaldttt** [comment]
Yes, Neovim doesn't support vim9script. You have to use vim with version 9+ to use this plugin.
